### ISSUE TITLE
Implement the new adapter testing framework

### ISSUE THREAD

**Issue by dbeatty10** [dbeatty10/dbt-mysql#105]
### Describe the feature
Implement the [adapter testing framework](https://docs.getdbt.com/docs/contributing/testing-a-new-adapter) that is described in [Upgrading to v1.1 - For maintainers of adapter plugins](https://docs.getdbt.com/guides/migration/versions/upgrading-to-v1.1#for-maintainers-of-adapter-plugins).

**Comment by shiyuhang0** [comment]
Can I try for this?

**Comment by dbeatty10** [comment]
Yes, that would be awesome if you pick up this issue @shiyuhang0 !

The current version in the `main` branch has already been upgraded to v1.1 in #101 (but not released in a new version yet), so it should be ready for you.

Let me know if you run into problems or need any help!
