### ISSUE TITLE
Is this project dead?

### ISSUE THREAD

**Issue by lucasfcnunes** [dbeatty10/dbt-mysql#166]
Hey, I'm a fan of this project and I really appreciate your work on dbt-mysql. But I'm wondering what's going on with the updates. It's been almost a year since the last release and there are still some issues with dbt-core compatibility.
I know you're probably busy and this is a community project, but it would be awesome to have access to the latest features of dbt-core.
Is there any chance you could release a new version soon or point me to an alternative fork that works better?

Thanks for your time and effort!

---

Relevant points:
- [dbt-core@^1.2 (to 1.7)](https://github.com/dbeatty10/dbt-mysql/issues/created_by/dataders) issues are still open
- almost 1 year since latest release (https://github.com/dbeatty10/dbt-mysql/releases/tag/v1.1.0, 2023-02-05)
- only 15 commit since last release https://github.com/dbeatty10/dbt-mysql/compare/v1.1.0...main
- 1.4 is ~7 months in the source code with no release https://github.com/dbeatty10/dbt-mysql/pull/146
- this project is the [de facto official dbt-mysql](https://docs.getdbt.com/docs/core/connect-data-platform/mysql-setup) (being community and all)

**Comment by dbeatty10** [comment]
Thanks for taking the time to reach out @lucasfcnunes!

@mwallace582 has joined me as a maintainer, and we're working towards releases to address the [dbt-core@^1.2 (to 1.7)](https://github.com/dbeatty10/dbt-mysql/issues/created_by/dataders) issues that are still open.

One of the blockers has been migrating the CI from CircleCI to GitHub Actions, which just got solved in #162.

While we don't have committed timelines for these releases, we're actively working towards getting up to 1.5 released (at a minimum). The bulk of the features that are specific to v1.5 are covered in https://github.com/dbeatty10/dbt-mysql/pull/163. And a bulk of those specific to v1.4 were covered in https://github.com/dbeatty10/dbt-mysql/pull/146.

Is there a specific version of dbt-core that you're hoping gets supported soon?

**Comment by lucasfcnunes** [comment]
@dbeatty10 You're awesome! I appreciate how quickly you got back to me.

> Is there a specific version of dbt-core that you're hoping gets supported soon?

I'm looking forward to 1.7, which is the newest one right now 😊. It has some cool features that I want to try out, like:
- [Support storing test failures as views](https://github.com/dbt-labs/dbt-core/releases/tag/v1.7.0#:~:text=Support%20storing%20test%20failures%20as%20views%20(%236914))

**Comment by dbeatty10** [comment]
> I'm looking forward to 1.7, which is the newest one right now 😊. It has some cool features that I want to try out, like:
> 
> * [Support storing test failures as views](https://github.com/dbt-labs/dbt-core/releases/tag/v1.7.0#:~:text=Support%20storing%20test%20failures%20as%20views%20(%236914))

That is a cool feature 😎

I'm going to close this one in favor of the issues related to [dbt-core@^1.2 (to 1.7)](https://github.com/dbeatty10/dbt-mysql/issues/created_by/dataders).

In the meantime, thanks again for pinging us -- looking forward to you being able to try out v1.7 with dbt-mysql.

**Comment by mwallace582** [comment]
Hi @lucasfcnunes,
We have just released several alpha versions of the `dbt-mysql` plugin which support the latest versions of `dbt-core`.
`1.2.0a1`, `1.3.0a1`, `1.4.0a1`, `1.5.0a1`, `1.6.0a1`, `1.7.0a1` ([See on PyPi](https://pypi.org/project/dbt-mysql/#history))

Please give these alpha versions a try and let us know if you encounter any issues. We will ship official releases once we're confident that they're stable.

There have been a bunch of new features and changes introduced with each new `dbt-core` minor release, and `dbt-mysql` doesn't currently support all of the new features.
DBT publishes [a checklist of recommended adapter changes for each new minor version](https://github.com/dbt-labs/dbt-core/discussions?discussions_q=%22Adapter+Maintainers%3A+Upgrading%22+), and we have not yet caught up with all of them (with the exception of 1.4 and 1.5).
I plan to gradually work through these checklists in my free time, but would welcome help from the broader community.

We hope that publishing all of these versions (even without the new features) will be a net gain, and fix the version incompatibilities which have been an issue for this adapter lately.

Regarding the "storing test failures as views" feature, the [update checklist for 1.7](https://github.com/dbt-labs/dbt-core/discussions/8307) mentions that the feature shouldn't require changes to the adapter, although we haven't added the new tests ensuring that it works.

**Comment by lucasfcnunes** [comment]
@mwallace582

We are using the 1.7.0a1 since 2024-01-21 with no issues (`requirements.txt` part below). Thanks!

```requirements.txt
# (...)
dbt-core~=1.7
dbt-mysqldbt-mysql~=1.7.0a1
dbt-clickhouse~=1.7
dbt-postgres~=1.7
# (...)
```
