### ISSUE TITLE
Test MySQL 5.6

### ISSUE THREAD

**Issue by dbeatty10** [dbeatty10/dbt-mysql#22]
MySQL 5.6 doesn't end support until [Feb 2021](https://en.wikipedia.org/wiki/MySQL#cite_ref-51:~:text=Feb%202021). We should test of dbt-mysql works or not for this version of MySQL.

Preferably, this testing would be automated within CI.

[WITH (Common Table Expressions aka CTE)](https://dev.mysql.com/doc/refman/8.0/en/with.html) aren't supported until MySQL 8.0, so that could be a big gotcha if they are used under the covers at all.

**Comment by AndersonReyes** [comment]
I can help with this as my team just used this package to actually do a test run locally (our db is mysql 5.6) but this prob depends on #9  to make it easy to install deps. Should I do both in one go? should be simple

**Comment by AndersonReyes** [comment]
Also how you want to structure the tests? I was thinking just regular dockerfile and docker compose to manage all the db containers and just multiple spec files for each db

**Comment by AndersonReyes** [comment]
but I agree the ctes in the adapter tests are a pain
```bash
dbt.exceptions.RuntimeException: Runtime Error in model passing_model (models/passing_model.sql)
  ('42000', "[42000] [MySQL][ODBC 8.0(w) Driver][mysqld-5.6.50]You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near '__dbt__CTE__ephemeral as (\n\n\nwith my_cool_cte as (\n  select name, id from dbt_te' at line 4 (1064) (SQLExecDirectW)")
```

**Comment by AndersonReyes** [comment]
Word thanks bro you had work on it already👍🏾👍🏾
