### ISSUE TITLE
Add to list of adapters at docs.getdbt.com

### ISSUE THREAD

**Issue by dbeatty10** [dbeatty10/dbt-mysql#23]
[Directions for adding to docs.getdbt.com](https://github.com/fishtown-analytics/dbt/issues/1153#issuecomment-628818404):

1. Add a new file for the mysql plugin within [this folder](https://github.com/fishtown-analytics/docs.getdbt.com/tree/master/website/docs/docs/supported-databases) (follow the format for existing plugins)
2. Add a link to this new file in [the sidebar](https://github.com/fishtown-analytics/docs.getdbt.com/blob/master/website/sidebars.js#L12)

The new plugin should show up in a local build of the docs for dbt core.

Here are some existing examples:
https://docs.getdbt.com/docs/supported-databases/profile-mssql

**Comment by dataders** [comment]
bumping this with the blurb I'm adding to all the undocumented adapters

> The [Available Adapters](https://docs.getdbt.com/docs/available-adapters) page is one of the dbt community's most-visited docs pages. It would be of great benefit for first-time visitors to the dbt docs to see:
> 1. that this adapter is a possible option for using dbt-core, and
> 2. how many large the dbt ecosystem of support databases is.
> 
> https://github.com/dbt-labs/docs.getdbt.com/issues/1489 exists to address this with all as-of-yet undocumented adapters.
> 
> We just released [Documenting a new adapter](https://docs.getdbt.com/docs/contributing/documenting-a-new-adapter), a new guide on how to add an adapter to the Available Adapters page. I'd love to see this adapter on that page, so feel free to reach out with any questions/blockers by either replying to this issue, or posting in the #adapter-ecosystem channel of the dbt Community Slack.
> 
> Looking forward to the contribution!

**Comment by dbeatty10** [comment]
Thank you for [adding this](https://github.com/dbt-labs/docs.getdbt.com/pull/1680) @TylerHillery!
- https://docs.getdbt.com/docs/supported-data-platforms
