### ISSUE TITLE
Test with current versions of MariaDB

### ISSUE THREAD

**Issue by dbeatty10** [dbeatty10/dbt-mysql#32]

**Comment by dbeatty10** [comment]
## Attempt
I did a quick tests of MariaDB 10.5 (with both dbt 0.19.0rc1 and 0.18.1) using the mysql-connector-python driver.

## Result
Neither worked out-of-the-box.

## Next steps
The best move might be to give MariaDB a stand-alone GitHub repository.

An alternative would be keep it within the `dbt-mysql` package, but create a separate `mariadb` adapter.

Either way, we'll probably need to install the [mariadb](https://mariadb.com/resources/blog/how-to-connect-python-programs-to-mariadb/) package from PyPi.

**Comment by dbeatty10** [comment]
[This MariaDB bug](https://jira.mariadb.org/browse/MDEV-22781) is a bit of a show-stopper. It will affect any ephemeral models used within a view.

"A fix for this bug was pushed into 10.2", but I'm not sure if this fix has made it into any public releases by MariaDB yet.

**Comment by dbeatty10** [comment]
From 2021-02-22: [MariaDB 10.5.9, 10.4.18, 10.3.28 and 10.2.37 now available](https://mariadb.org/mariadb-10-5-9-10-4-18-10-3-28-and-10-2-37-now-available/).

This should fix [this bug](https://jira.mariadb.org/browse/MDEV-22781):
![image](https://user-images.githubusercontent.com/44704949/109012221-00b15080-766f-11eb-8c89-3bca1abd36e7.png)

**Comment by antoniopaisfernandes** [comment]
Hi @dbeatty10!

Sorry 🤷‍♂️ for troubling you.
If you know, can you share your plans about MariaDB? It is going in the dbt-mariadb direction or integrating in dbt-mysql?

Best regards

**Comment by dbeatty10** [comment]
No trouble at all, @antoniopaisfernandes!

For now, the easiest approach is to keep it within the `dbt-mysql` package, but create a separate `mariadb` adapter. This work is completed now, and it will be included in the next release 🎉

This decision is not a one-way door, and we still preserve the option to change direction in the future (see "Future options" below).

## Potential gotachas with the `mariadb` adapter
The integration tests for snapshots aren't passing yet. It might be related to [this](https://github.com/dbeatty10/dbt-mysql/issues/75) issue. So snapshots may or may not work for you right now.

## Future options
1. Keep it within the `dbt-mysql` package
1. Stand-alone GitHub repository for MariaDB
    * Even right now, anyone could fork this project and then install their fork via [these instructions](https://docs.getdbt.com/docs/available-adapters#installation).
