### ISSUE TITLE
Installation problems   Could not find adapter type mysql!

### ISSUE THREAD

**Issue by Gschiavon** [dbeatty10/dbt-mysql#64]
--

**Comment by MarcoMedrano** [comment]
Hello, @Gschiavon what was the issue? I am having it using airbyte and custom normalization.

**Comment by MarcoMedrano** [comment]
[Solved](https://stackoverflow.com/questions/64144483/could-not-find-adapter-type-bigquery), the [adapter/plugin](https://docs.getdbt.com/docs/available-adapters) was not installed (and is not even listed on that page).
Just install it with pip or pip3
```sh
pip install dbt-mysql
```
